### ISSUE TITLE
$T namespace documentation

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/LightningTestingService#16]
Is there any documentation on the functions available in the $T namespace? I can figure out what is in the examples, but curious as to whether there are any nuances (e.g. does $T.waitFor() have a configurable timeout) or additional methods that don't appear in the examples.

**Comment by keirbowden** [comment]
Regarding the $T.waitFor() timeout - would I be correct in thinking that this will actually wait forever and it is the Jasmine asynchronous test timeout that will actually kill the spec?

**Comment by esalman-sfdc** [comment]
$T is declared in [testutil](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/staticresources/testutil.resource) 

The file has documentation for the helper methods it exports. 

Its basically using JavaScript module pattern similar to one described in https://developer.salesforce.com/blogs/developer-relations/2016/12/lightning-components-code-sharing.html

**Comment by keirbowden** [comment]
The one static resource I haven't yet looked at! I was assuming that it was part of the lightning components framework a la $A.
