### ISSUE TITLE
How does SFDX get the test results?

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/LightningTestingService#28]
I've written a couple of custom reporters for Salesforce/Lightning/Jasmine which I'd like to port over to LTS and integrate with SFDX.  Are you able to share how the SFDX CLI gets the test results when executing "sfdx force:lightning:test:run" - e.g. is it a screen scrape or does something get inserted etc. Thanks.

**Comment by esalman-sfdc** [comment]
Hey @keirbowden  by default the command waits for an element with id="run_results_full". See [jasmineReporter](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/staticresources/jasmineReporter.resource) for the format it expects. 

Currently, there are two reporters on the app, Jasmine's default html reporter whose report you see, and a custom reporter whose results are hidden by read by sfdx.

We can streamline the interface and add some documentation around this to make this part of integration easier to customize.
 
Things like Id of the element to wait for or the browser to use are configurable via a config file which that can be passed in "-f" option. 

Sample config file:
```
{
	"webdriverio": {
		"desiredCapabilities": {
			"browserName": "chrome"
		}
	},
	"outputDivId": "run_results_full"
}
```

**Comment by keirbowden** [comment]
Awesome - thanks!
