### ISSUE TITLE
Looking for reference about $T

### ISSUE THREAD

**Issue by skosaka** [forcedotcom/LightningTestingService#33]
Team,
I looked over the sample test resources and found $T namespace. Are there any reference about the methods in this namespace like $T.fireApplicationEvent? I would like to know what and how to use those methods.

**Comment by cdengSFDC** [comment]
You can take a look at [lts_testutil.resource](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/staticresources/lts_testutil.resource).

**Comment by skosaka** [comment]
Oh, I overlooked it. Thank you so much!!
