### ISSUE TITLE
How to interact with the custom components using LTS ?

### ISSUE THREAD

**Issue by AntonMichael** [forcedotcom/LightningTestingService#43]
For Example I am having component c:uiInputText which has a attribute "property". My custom component extends SFDC lightning component ui:inputText and I will set the value attribute via the property attribute my custom component. 

Now when I tried to set the value for the custom component, I am not able to set and also I am not seeing any error. Any idea would be great

Sample snippet:

var ruleNameCMP = component.find("ruleid");
ruleNameCMP.set("v.property","value 1"));

**Comment by esalman-sfdc** [comment]
Kindly see thread [at](https://github.com/forcedotcom/LightningTestingService/issues/42)
