### ISSUE TITLE
Overlapping of rendered components with the App Components 

### ISSUE THREAD

**Issue by Vanathi21** [forcedotcom/LightningTestingService#45]
In LTS Examples, we are using the custom component "lts_jasmineRunner.cmp". In my case when we tuned as per my requirement (For Example. we tried by including the necessary scripts and jasmine libraries as in the custom component "lts_jasmineRunner" in my App) , The problem was that we are facing overlapping between the rendered component and the App Components. 

We suspect that the Rendering component in the div element might causing the collision with the App components. Could you please help on getting this resolved ?

**Comment by esalman-sfdc** [comment]
I don't think I understand the question completely. For example what do you mean by App Components. Is it possible for you to share a github repository, a unmanaged package or at minimum a gist to make it easy for us to collaborate.

**Comment by Vanathi21** [comment]
App Component what is referred is the Base Component for my Entire App(Parent Component).
Similar to the Lightning App which contains Lightning Components.(aura:application containing aura:components.,For Eg: **Salesforce Lightning Experience**). In My case we are having an Lightning aura:application similar to that of Salesforce Lightning Experience. And In that App (main.app) we are including the necessary scripts and styles necessary for LTS. I have added the snippet below

<aura:application template="c:templatemyApp" access="GLOBAL" extends="force:slds">           
    <ltng:require scripts="{!join(',', 
                           $Resource.lts_jasmine + '/lib/jasmine-2.6.1/jasmine.js',
                           $Resource.lts_jasmine + '/lib/jasmine-2.6.1/jasmine-html.js',
                           $Resource.lts_jasmineboot,
                           $Resource.lts_testutil,
                           $Resource.Test,     
                           )}"
                  styles="{!join(',', 
                          $Resource.lts_jasmine + '/lib/jasmine-2.6.1/jasmine.css',
                          $Resource.appStatic +
                          '/css/font-awesome.min.css'       
                          )}"
                  afterScriptsLoaded="{!c.initApp}" />                      
    
    <div aura:id="myAppContainer" id="myAppContainer" class="myAppContainer">        
        
        <div aura:id="renderTestComponents" id="renderTestComponents"  ></div>
        
    </div>
</aura:application>

In the Static-resources, I have test cases written. Below is my sample case.

describe('eg', function() {
    it("example", function(done) {
        $T.createComponent("c:myApp", {}, true)       
        .then(function(component) {
            setTimeout(function() {
               // Necessary Actions Here
            }, 4000);
            if(document.readyState == "complete") {  
                expect(document.URL).toContain("settings");
            }
            done();
        }).catch(function(e) {
            done.fail(e);
        });
    });
});

In that i have made the rendering "True". So that in my App that component got rendered and that created the overlapping with the Application.Without Rendering the component i wasn't able to set attributes values(In my case setting the value to the uiInputText component) and see that updated values in the UI . And Also clearing rendered components doesn't save the changes we made in the component.

Based on the App base component i wanna do the functionality testing. So we are trying to get the scope of the base component. Will this rendering of components will give us the scope of those base component ? And Could you suggest some way to handle this ?

**Comment by esalman-sfdc** [comment]
ok so looks like instead of using lts_jasmineRunner.cmp you are trying to create your on your runner to incorporate some of the customizations you needs. And from what I understand by 'overlapping' you mean jasmine results UI showing up on top of what your component's UI. Are you [providing](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/aura/lts_jasmineRunner/lts_jasmineRunner.cmp#L8) jasmine a placeholder to render its UI? If not one may be getting created automatically for you via [this](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/staticresources/lts_jasmineboot.resource#L71) and it may not be showing up where you want.

Regarding you other question, in general, you don't need to render a component to set its attribute value although you would need to rendered if you want to see the UI or if you want to interact with the DOM belonging to your namespace.

**Comment by Vanathi21** [comment]
We are seeing the overlapping issue when we have jasmine runner (lts_jasmineRunner) separately. We are having our App container in a div. You are having a div rendering the component. So While doing this $T.createComponent(cmp, {}, true), We are seeing the overlapping. Please see the screenshot.

![overlap issue](https://user-images.githubusercontent.com/32476731/33160669-2b79a4b8-d044-11e7-96bb-5f4c32d891f4.png)

**Comment by esalman-sfdc** [comment]
It seems related to the styling being used my the component being rendered. As a quick workaround, may be try flipping the order of 'jasmineHtmlTestResults' and 'renderTestComponents' in lts_jasmineRunner. Unfortunately I can't be more specific without having a repro case.
