### ISSUE TITLE
ERROR:  Cannot read property 'endsWith' of undefined.

### ISSUE THREAD

**Issue by chendagit** [forcedotcom/LightningTestingService#47]
run this command with sfdx-cli/6.0.16-3780698 (darwin-x64) node-v8.6.0

`sfdx force:lightning:test:run`

ERROR:  Cannot read property 'endsWith' of undefined.

**Comment by chendagit** [comment]
found the same issue with discussion: https://github.com/forcedotcom/LightningTestingService/issues/38

**Comment by sjurgis** [comment]
I think I've found the problem:
`~/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/lightning/lightningTestApi.js:196`
expects default test app name to be jasmineTests...
