### ISSUE TITLE
Unmanaged package (without examples) does not contain the Jasmine "app"

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/LightningTestingService#50]
When downloading the unmanaged package for Jasmine (without examples - the first URL here https://github.com/forcedotcom/LightningTestingService/releases), the lightning app to run the jasmine tests is missing i.e https://{mydomain}/c/jasmineTests.app

If I install the unmanaged package with examples, then the app is there. Is this expected or am I supposed to somehow create my own app using the Jasmine source files?

**Comment by esalman-sfdc** [comment]
It is by design. Package contains the component which can be used to compose test apps.
