### ISSUE TITLE
Build error: plugin salesforcedx is not digitally signed

### ISSUE THREAD

**Issue by pozil** [forcedotcom/LightningTestingService#53]
While building my CI with Travis I got an error while installing Salesforce DX and I just noticed that this repository is also impacted by it (build is failing at time of writing).

When running sfdx `plugins:install salesforcedx`the CLI will output a blocking prompt which breaks CI:
```
Installing plugin salesforcedx... Checking for digital signature.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: 
```

I am bit surprised that this official plugin is not signed so perhaps it's a bug in the plugin build chain.

Here is how I fixed it based on the [official DX doc](https://developer.salesforce.com/blogs/2017/10/salesforce-dx-cli-plugin-update.html):

1. Create a plugin whitelist file named `unsignedPluginWhiteList.json` in the `config` directory with the following content:
```
[
    "salesforcedx"
]
```

2. Move the whitelist file in a specific directory before running the plugin install command:
`mv config/unsignedPluginWhiteList.json $HOME/.config/sfdx/.`

I hope that it helps.

**Comment by amphro** [comment]
Hey @pozil - confirmed the issue. We will work on resolving this. On a side note, you shouldn't need to install salesforcedx as it is now bundled with the CLI. If you comment out that line in your CI, you can still run force commands and see the plugin version with `sfdx plugins --core`. The only reason to install the plugin is if you need to hardcode to a specific version.

**Comment by pozil** [comment]
Thx @amphro for confirming this.
I must admit that I did a copy paste from this repo so you might want to remove `plugins:install salesforcedx` from `.travis.yml`.

**Comment by amphro** [comment]
Yeah, I just talked to @esalman-sfdc about that. Thanks for the suggestion!

**Comment by esalman-sfdc** [comment]
Thanks @pozil for the heads up. I have updated the CI configs used by this repository.
