### ISSUE TITLE
Can't install unmanaged package

### ISSUE THREAD

**Issue by sdruckerfig** [forcedotcom/LightningTestingService#57]
Trying to install the unmanaged package from this url:
https://test.salesforce.com/packaging/installPackage.apexp?p0=04tJ00000006jBu

It's not accepting my org's username/password.

**Comment by esalman-sfdc** [comment]
Login to your org and install by only copy/pasting the relative url portion. That is,

YOUR_DOMAIN_AFTER_LOGIN/packaging/installPackage.apexp?p0=04tJ00000006jBu

As preferred use of LTS package is with scratch orgs, host "test.salesforce.com" under the releases tab points to the sandbox instances (scratch orgs reside on sandbox servers).
