### ISSUE TITLE
saucelabs environment vars

### ISSUE THREAD

**Issue by froucher** [forcedotcom/LightningTestingService#60]
Hi, 

I am trying to connect LTS with saucelabs.com, and I has successfully connected with this command:

```sh
sfdx force:lightning:test:run -f config.json
```

And the following configuration in config.json

```json
{
  "webdriverio": {
    "host": "ondemand.saucelabs.com",
    "port": "80",
    "user": "saucelabs_user",
    "key": "secretkey",
    "desiredCapabilities": {
      "browserName": "chrome",
      "chromeOption": {
        "args": [ "--no-sandbox" ]
      }
    }
  }
}
```

This run :)

But the question is:

_Can I use two environment variables instead of push these secrets to the git repository?_

This is a [Best Practices](https://wiki.saucelabs.com/display/DOCS/Best+Practice%3A+Use+Environment+Variables+for+Authentication+Credentials) and it is very interesting for continuous integration environment.

Sample:

```sh
export SAUCE_USERNAME=saucelabs_user
export SAUCE_ACCESS_KEY=secretkey
sfdx force:lightning:test:run -f config.json
```

Thanks.

**Comment by esalman-sfdc** [comment]
When running on CI, may be you could generate a config file from a template replacing placeHolders with values read from env variables. 
For localhost, you could use a config which is in gitignore (assuming you use git)

**Comment by froucher** [comment]
I deployed lightning testing services in CI with this workaround. Thanks for the answer.
