### ISSUE TITLE
lightning:select breaks test with Error ID: 2004951991-66946

### ISSUE THREAD

**Issue by paulroberttaylor** [forcedotcom/LightningTestingService#62]
I just spent quite some time tracking down why a simple test was breaking, as the error message didn't give any indication of what the problem is.

I'm using a fresh install using the CLI install command.  All the tests work apart from the data service tests which have already been reported.

How to replicate:

Add a lightning:select to the markup without a label (not a blank label, the entire label attribute missing).

Notes:

While label is a required attribute, a lightning:select renders, and does not error, when used on a component normally without the attribute.

**Comment by esalman-sfdc** [comment]
Thanks @paulroberttaylor for reporting the error. Underlying issue is that Lightning framework is classifying the exception as salesforce issue instead of bubbling it up as a developer error (hence generating the Error Id instead of letting the error message bubble up). Its not specific to LTS, and can be reproduced by creating a custom application with following markup.

```
<aura:application >
    <lightning:select name="selectItem" onchange="{!c.doSomething}">
        <option value="">choose one...</option>
        <option value="1">one</option>
        <option value="2">two</option>
    </lightning:select>
</aura:application>
```

Navigating to the app would result in following,
> This page has an error. You might just need to refresh it. Aura.loadComponent(): Failed to initialize application. An internal server error has occurred Error ID: 1448037039-25598 (1552973958)

I have created a bug (W-4745082) for the team that owns the area and attached your feedback to it. I plan on closing this issue out as the issue is specific to LTS.

**Comment by paulroberttaylor** [comment]
@esalman-sfdc Thanks for the feedback.  I agree this isn't related to the testing framework so I'm happy to close this myself as it's been raised with the relevant team.

**Comment by Maledong** [comment]
@paulroberttaylor：Have you got any docs about the error in detail info?
You see that the error below is TOO ROUGH for us to understand, I think since you've given us an ERROR code, so you should have something mapping to which error in details……?!

>This page has an error. You might just need to refresh it. Aura.loadComponent(): Failed to initialize application. An internal server error has occurred Error ID: 1448037039-25598 (1552973958)

**Comment by Maledong** [comment]
@esalman-sfdc ：Have you got any docs about the error in detail info?
You see that the error below is TOO ROUGH for us to understand, I think since you've given us an ERROR code, so you should have something mapping to which error in details……?!

>This page has an error. You might just need to refresh it. Aura.loadComponent(): Failed to initialize application. An internal server error has occurred Error ID: 1448037039-25598 (1552973958)

**Comment by cyberjus** [comment]
@esalman-sfdc I just spent forever trying to debug a similar problem related to lightning:select. Lightning select was working for me on Lighting Page but not in a Lightning App, prompting a similar error. 

Try adding the label attribute to the component. The framework says this is required, even though it does not prompt it. That finally resolved it for me.
