### ISSUE TITLE
Question on `sfdx force:lightning:test:install -t jasmine` 

### ISSUE THREAD

**Issue by tsneed290** [forcedotcom/LightningTestingService#71]
I was curious if it is expected that `sfdx force:lightning:test:install -t jasmine` is run for each CI job? I ask this because after running `sfdx force:lightning:test:install -t jasmine` I then ran `sfdx force:source:pull`, expecting to see the Jasmine test runner component show up in my local project, so that I could check it into my project's SCM. Unfortunately that source code was not pulled.

I'm still getting used to SFDX's project structure, and from what I can tell, I cannot use my Force.com IDE plugin for Eclipse to connect to this scratch org (am I wrong there?) to pull the source.

Thanks for any insights!

-Tim

**Comment by esalman-sfdc** [comment]
Idea with `sfdx force:lightning:test:install` is that you install the package into the scratch org before pushing your source (and tests) to it and keep your code decoupled from the LTS code (enabling you to digest new versions of the package more easily).

If you prefer to keep the copy of LTS code in your repo (for more control or customization), you are welcome to do that (there are multiple ways). You could retrieve installed package source via `sfdx force:mdapi:retrieve` by passing in package name or get the source directly from this repository ([sfdx-waw-plugin ](https://github.com/wadewegner/sfdx-waw-plugin#pull-open-source-into-your-project) plugin's `sfdx waw:source:oss` command can help with that)

Original Force.com IDE does not support SFDX source format. There is however Force IDE 2 (being deprecated in favor of VS Code extensions) which does. This [blog post](https://developer.salesforce.com/blogs/2018/02/salesforce-extensions-vs-code.html) has some more details on the future IDE investments being made for force.com platform.

**Comment by tsneed290** [comment]
Thanks for the help!
