### ISSUE TITLE
Reporting does not escape every attribute in Junit format.

### ISSUE THREAD

**Issue by louis-bompart** [forcedotcom/LightningTestingService#84]
When running the script, the reporter does not escape properly the `name` attribute of the `testcase` attribute (and the `classname` attribute too I think).

This can lead to invalid xUnit report, preventing some tools to parse them properly.

Here's an example with the bundled test:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.lightning" timestamp="2018-08-31T01:59:11+00:00" hostname="xxxxxxxxx" tests="18" failures="0"  errors="0"  time="4.45">
        ...
        <testcase name="Lightning Component Testing Examples : c:egConditionalUI : renders only the "truthy" (conditional) portion of the user interface" classname="" time="0.05">
        </testcase>
        ...
    </testsuite>
</testsuites>```

**Comment by ahayes91** [comment]
You'll have to escape " characters in the name attribute yourself - this is true in any Lightning component, as per Salesforce documentation:
"Double quotation marks are reserved for enclosing attribute values, and must be escaped in strings."
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/expr_operators.htm
