### ISSUE TITLE
LTS for blur component event

### ISSUE THREAD

**Issue by vishalsfdc98** [forcedotcom/LightningTestingService#91]
Hi,

I have written onblur() function with aura:id="dummyId" inside my <Lightning:input> tag and trying simulating same by using document.getElementById("dummyId").dispatchEvent(event); 

But this is giving error saying "Failed: Cannot read property 'dispatchEvent' of null".

Kindly assist.

**Comment by diervo** [comment]
You are mixing concepts, `aura:id` has nothing to do with the DOM. The attribute `auraId` is used to find components within aura:`cmp.find('dummyId')`.

If you want to search for your lightning input I suggest you use classes (.lightningInput) or something like that.

As a friendly note, `github issues` is not the right forum to ask questions about your particular code. Use StackOverflow next time which will help better the community.
