### ISSUE TITLE
Unable to install LTS with SFDX

### ISSUE THREAD

**Issue by BindiyaGowri** [forcedotcom/LightningTestingService#93]
Issue with Lightning Test Service installation.

Throws error when tried to intsall LTS using SFDX due to requiredSecurityType argument which is not a valid parameter for the LTS install command.

sfdx force:lightning:test:install --SecurityType AllUsers
ERROR running force:lightning:test:install:  Unexpected arguments: --SecurityType, AllUsers
See more help with --help

![image](https://user-images.githubusercontent.com/22540621/60259950-041e9280-98f6-11e9-8c3b-5c62dae316b3.png)

**Comment by KrisGraySFDC** [comment]
Investigating, thank you Bindiya.

**Comment by KrisGraySFDC** [comment]
A fix has been identified. Because of the weekend, it'll probably go out next week. Sorry.

**Comment by Sheing** [comment]
Having similar problem, need a fix asap.

**Comment by KrisGraySFDC** [comment]
Fix has been merged and will go out with the next update of the CLI.
