### ISSUE TITLE
Fails On Page Load w/ "Freeze Javascript Prototype" Enabled

### ISSUE THREAD

**Issue by johnzhao9** [forcedotcom/LightningTestingService#97]
Using LTS 1.4 With Examples (Package Version ID 04tJ00000006jC9) in a Winter '20 Enterprise Scratch Org (Org ID 00D0t0000009Srf - granted access)

To reproduce:
1. Enable the "Freeze Javascript Prototype" option from Setup | Session Settings
 
![image](https://user-images.githubusercontent.com/13734035/66499808-20e66c80-ea86-11e9-829e-d5fcfb414d57.png)

2. Try to load the [jasmineTests.app](https://github.com/forcedotcom/LightningTestingService/blob/master/lightning-component-tests/test/default/aura/jasmineTests/jasmineTests.app)

3. 
![image](https://user-images.githubusercontent.com/13734035/66500628-7cfdc080-ea87-11e9-88fc-dcc85e826a9a.png)

Addtionally:

The error in `aura_proddebug.js` looks like this (from the try catch in `function evaluate(src, key, sourceURL) {`):
```
TypeError: Cannot assign to read only property 'constructor' of object 'Error'
    at Object.getJasmineRequireObj.errors (jasmine.js:1966)
    at Object.getJasmineRequire.core (jasmine.js:49)
    at eval (lts_jasmineboot:18)
    at Proxy.eval (lts_jasmineboot:121)
    at Object.eval (eval at createEvalEvaluatorFactory (aura_proddebug.js:11669), <anonymous>:8:16)
    at Object.eval [as evalEvaluator] (aura_proddebug.js:11764)
    at evaluate (aura_proddebug.js:12095)
    at XMLHttpRequest.xhr.onload (aura_proddebug.js:13646)
```

Hopefully it'll be as simple as updating the Jasmine library to fix the issue, not sure

**Comment by johnzhao9** [comment]
The freeze js prototype option just disappeared in scratch orgs. It was still in the scratch orgs created this morning
Not sure what's the implication of that, is it defaulting to true now for all orgs or the change is simply rolled back and we don't have to worry about this option anymore
It also disapppeared in API48 version's documentation

**Comment by KrisGraySFDC** [comment]
I'm pretty sure we're solving that problem a different way now, and we do not plan to implement the Freeze prototype JS further.

**Comment by johnzhao9** [comment]
@KrisGraySFDC Awesome thanks for update on this , that takes care of it. I'll close the issue.
