### ISSUE TITLE
Installing with sfdx causes a GACK

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/LightningTestingService#98]
Either using package Id or just a regular command ends up with a GACK:
```
ERROR running force:lightning:test:install:  An unexpected error occurred. Please include this ErrorId if you contact support: 1418695951-149805 (-930115222)
ERROR running force:package:install:  An unexpected error occurred. Please include this ErrorId if you contact support: 2080841443-255616 (-930115222)
```

**Comment by johnzhao9** [comment]
Getting the same issue
```
Successfully authorized test-zcbcxdvu9q3i@example.com with org ID 00D5600000029pYEAQ
ERROR:  An unexpected error occurred. Please include this ErrorId if you contact support: 1479231602-1959835 (-930115222).
```

Seems to be instance-specific, confirmed this happening in three CS42 scratch orgs but not CS45 and CS4 orgs

**Comment by sjurgis** [comment]
Error has changed into:
> ERROR running force:package:install:  The package version is not fully available. If this is a recently created package version, try again in a few minutes or contact the package publisher.

**Comment by johnzhao9** [comment]
Issue seems to be resolved on my side

**Comment by KrisGraySFDC** [comment]
Anyone still having this issue?
